CC = gcc
CFLAGS = -g
LDFLAGS = -lm

PROGRAMS = cadeia-ifs cadeia-if-else \
	   switch switch2 switch3 switch4 \
           switch-vogal switch-minuscula \
           if-minuscula calc menu


all: $(PROGRAMS)

clean:
	rm -f *.o *~ $(PROGRAMS)
